import colors from "@/utils/colors";
import clsx from "clsx";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="dark">
        <body
          className={clsx(
            "mx-auto min-h-screen max-w-screen-xl px-6 py-12 font-sans md:px-12 md:py-20 lg:px-24 lg:py-0 relative",
            inter.className,
            colors.background,
            colors.body
          )}
        >
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
